# Generated by Django 3.2.7 on 2021-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=4000),
        ),
    ]
