# Generated by Django 3.2.7 on 2021-11-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20211029_2322'),
        ('faq', '0002_auto_20211031_1525'),
    ]

    operations = [
    ]
