# Generated by Django 2.2.24 on 2021-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_merge_0002_auto_20211029_2322_0002_auto_20211031_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
