# Generated by Django 3.2.7 on 2021-10-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nomorTelp', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('syaratPeserta', models.CharField(max_length=100)),
            ],
        ),
    ]
