# Generated by Django 3.2.7 on 2021-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaksin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaksinBogor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nomorTelp', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('syaratPeserta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaksinDepok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nomorTelp', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('syaratPeserta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaksinJakarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nomorTelp', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('syaratPeserta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaksinTangerang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('nomorTelp', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('syaratPeserta', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Vaksin',
            new_name='VaksinBekasi',
        ),
    ]
