# Generated by Django 3.2.7 on 2021-11-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaksin', '0003_auto_20211029_2322'),
        ('vaksin', '0003_auto_20211031_1525'),
    ]

    operations = [
    ]
