# Generated by Django 3.2.7 on 2021-10-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=9)),
                ('tahun', models.CharField(max_length=4)),
                ('penambahanKasusPositif', models.CharField(max_length=9)),
                ('PositifKumulatif', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='VaksinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=9)),
                ('tahun', models.CharField(max_length=4)),
                ('vaksin_1_kali', models.CharField(max_length=9)),
                ('vaksin_2_kali', models.CharField(max_length=9)),
                ('belum_vaksin', models.CharField(max_length=9)),
            ],
        ),
    ]
