# Generated by Django 3.2.7 on 2021-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(default='', max_length=9)),
                ('tahun', models.CharField(default='2021', max_length=4)),
                ('penambahanKasusPositif', models.CharField(max_length=9)),
                ('PositifKumulatif', models.CharField(max_length=9)),
            ],
        ),
    ]
