# Generated by Django 3.2.7 on 2021-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='sumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
