# Generated by Django 3.2.7 on 2021-10-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddata',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='coviddata',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='vaksindata',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='vaksindata',
            name='tahun',
        ),
    ]
