# Generated by Django 3.2.7 on 2021-11-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='bulan',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='tahun',
            field=models.CharField(default='2021', max_length=4),
        ),
    ]
