# Generated by Django 3.2.7 on 2021-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0002_auto_20211031_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddata',
            name='bulan',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='coviddata',
            name='tahun',
            field=models.CharField(default='2021', max_length=4),
        ),
        migrations.AddField(
            model_name='vaksindata',
            name='bulan',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='vaksindata',
            name='tahun',
            field=models.CharField(default='2021', max_length=4),
        ),
    ]
