# Generated by Django 3.2.7 on 2021-11-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0003_auto_20211031_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaksinData',
        ),
    ]
