# Generated by Django 3.2.7 on 2021-11-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0002_auto_20211029_2322'),
        ('beranda', '0004_delete_vaksindata'),
    ]

    operations = [
    ]
