# Generated by Django 3.2.7 on 2021-10-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_nama', models.CharField(max_length=100)),
                ('rs_lokasi', models.CharField(max_length=20)),
                ('rs_alamat', models.CharField(max_length=100)),
                ('rs_url_gmaps', models.CharField(max_length=100)),
                ('rs_no_telp', models.IntegerField(max_length=20)),
                ('rs_kamar_tersedia', models.IntegerField()),
            ],
        ),
    ]
