# Generated by Django 3.2.7 on 2021-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumahSakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(choices=[('JK', 'Jakarta'), ('BO', 'Bogor'), ('DE', 'Depok'), ('TA', 'Tangerang'), ('BEK', 'Bekasi'), ('L', 'Luar Jabodetabek')], default='L', max_length=3)),
                ('alamat', models.CharField(max_length=100)),
                ('url_gmaps', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=15)),
                ('tersedia', models.CharField(choices=[('I', 'ICU'), ('K', 'Kamar'), ('IK', 'ICU dan Kamar')], default='IK', max_length=2)),
            ],
        ),
    ]
