# Generated by Django 3.2.7 on 2021-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumahsakit',
            old_name='rs_alamat',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='rumahsakit',
            old_name='rs_lokasi',
            new_name='lokasi',
        ),
        migrations.RenameField(
            model_name='rumahsakit',
            old_name='rs_nama',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='rumahsakit',
            old_name='rs_url_gmaps',
            new_name='url_gmaps',
        ),
        migrations.RemoveField(
            model_name='rumahsakit',
            name='rs_kamar_tersedia',
        ),
        migrations.RemoveField(
            model_name='rumahsakit',
            name='rs_no_telp',
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='kamar_tersedia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='no_telp',
            field=models.IntegerField(default=0),
        ),
    ]
