# Generated by Django 3.2.7 on 2021-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0002_auto_20211029_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahsakit',
            name='no_telp',
            field=models.CharField(max_length=15),
        ),
    ]
