# Generated by Django 3.2.7 on 2021-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0003_alter_rumahsakit_no_telp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumahsakit',
            name='kamar_tersedia',
        ),
        migrations.AddField(
            model_name='rumahsakit',
            name='tersedia',
            field=models.CharField(choices=[('I', 'ICU'), ('K', 'Kamar'), ('IK', 'ICU dan Kamar')], default='IK', max_length=2),
        ),
        migrations.AlterField(
            model_name='rumahsakit',
            name='lokasi',
            field=models.CharField(choices=[('JK', 'Jakarta'), ('BO', 'Bogor'), ('DE', 'Depok'), ('TA', 'Tangerang'), ('BEK', 'Bekasi'), ('L', 'Luar Jabodetabek')], default='L', max_length=3),
        ),
    ]
