# Generated by Django 3.2.7 on 2021-11-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0002_alter_oksigen_id'),
        ('oksigen', '0002_oksigen_domisili'),
    ]

    operations = [
    ]
