# Generated by Django 2.2.24 on 2021-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0003_auto_20211104_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='domisili',
            field=models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='oksigen',
            name='telepon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oksigen',
            name='url',
            field=models.CharField(max_length=40),
        ),
    ]
