# Generated by Django 3.2.7 on 2021-11-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0003_merge_0002_alter_oksigen_id_0002_oksigen_domisili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='domisili',
            field=models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], default='green', max_length=9),
        ),
    ]
