# Generated by Django 2.2.24 on 2021-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0004_alter_oksigen_domisili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
