# Generated by Django 2.2.24 on 2021-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0004_auto_20211105_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='alamat',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='oksigen',
            name='domisili',
            field=models.CharField(choices=[('isi data', ''), ('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], default='', max_length=9),
        ),
    ]
