# Generated by Django 2.2.24 on 2021-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0005_auto_20211105_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='domisili',
            field=models.CharField(choices=[('', 'isi data'), ('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], default='', max_length=9),
        ),
    ]
