# Generated by Django 2.2.24 on 2021-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0007_auto_20211105_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='domisili',
            field=models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi')], max_length=9),
        ),
    ]
