# Generated by Django 2.2.24 on 2021-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0008_auto_20211105_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='url',
            field=models.CharField(max_length=70),
        ),
    ]
