# Generated by Django 3.2.7 on 2021-11-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0002_auto_20211105_1116'),
        ('oksigen', '0009_auto_20211105_0827'),
    ]

    operations = [
    ]
