# Generated by Django 2.2.24 on 2021-11-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0009_auto_20211105_0827'),
        ('oksigen', '0002_auto_20211105_1116'),
    ]

    operations = [
    ]
