# Generated by Django 2.2.24 on 2021-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oksigen', '0010_merge_20211105_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oksigen',
            name='url',
            field=models.CharField(max_length=80),
        ),
    ]
