# Generated by Django 3.2.7 on 2021-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=30)),
                ('lokasi', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=0)),
                ('harga', models.IntegerField(default=0)),
            ],
        ),
    ]
