# Generated by Django 3.2.7 on 2021-10-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apd',
            name='jumlah',
        ),
        migrations.AddField(
            model_name='apd',
            name='img_source',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
