# Generated by Django 2.2.24 on 2021-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
